=== Taper21/local-api/example_raml/schemas/users.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "array",
    "description": "collection of users",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "type": "string"
            },
            "birthDate": {
                "type": "string"
            },
            "email": {
                "type": "string"
            },
            "firstName": {
                "type": "string"
            },
            "lastName": {
                "type": "string"
            },
            "gender": {
                "type": "string"
            },
            "status": {
                "type": "boolean"
            },
            "createdAt": {
                "type": "string"
            },
            "updatedAt": {
                "type": "string"
            },
            "idArray": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "points": {
                "type": "integer"
            }
        }
    }
}

=== Taper21/local-api/example_raml/examples/users.json
[
    {
        "id": "f5305tgr6jacq5mi",
        "birthDate": "1986-12-22",
        "email": "Concepcion.Ruecker10@gmail.com",
        "firstName": "Rosanna",
        "lastName": "Wilkinson",
        "gender": "female",
        "status": true,
        "createdAt": "2014-06-29T18:36:45.632Z",
        "updatedAt": "2014-06-29T18:36:45.632Z",
        "idArray": [
            "pimqbhu2wy4lsor",
            "wdvlc26yz1960f6r"
        ],
        "points": 79
    },
    {
        "id": "jzi6lffem93mzpvi",
        "birthDate": "1965-03-12",
        "email": "Sydnie68@gmail.com",
        "firstName": "Amani",
        "lastName": "Hickle",
        "gender": "male",
        "status": true,
        "createdAt": "2014-02-21T22:13:53.492Z",
        "updatedAt": "2014-02-21T22:13:53.492Z",
        "idArray": [
            "iysltnuasln89f6r",
            "ydu6xmwq4bowdn29",
            "9duq4m3x7f7ds4i",
            "gtfw16bpd8q41jor",
            "8xncyxkz8srftj4i",
            "i42k2e0xqvq85mi",
            "fqnu1gde5j6ecdi",
            "ojezva7csz2maemi",
            "h2nwl1ui9m620529"
        ],
        "points": 50
    },
    {
        "id": "c4pvegyo088v9529",
        "birthDate": "1936-05-14",
        "email": "Maci_Mueller39@gmail.com",
        "firstName": "Vena",
        "lastName": "Hartmann",
        "gender": "female",
        "status": true,
        "createdAt": "2014-06-03T19:34:09.045Z",
        "updatedAt": "2014-06-03T19:34:09.045Z",
        "idArray": [
            "c3qm2srvpdjkyb9",
            "dad2xkp7zpmygb9",
            "19ivtaibwm7bke29",
            "6sidgwze2fxvquxr",
            "8y2ihjwtzext7qfr",
            "k5c7yoj5exc4n29",
            "kna66d57nb384cxr",
            "tyo6w1c35w3a0pb9",
            "uule3fi1tpv9ggb9",
            "38y5wjzq18msfw29",
            "fpmjo3h70lmu0udi",
            "p0ru3sinr3ipy14i",
            "xl141gvv04lvj9k9",
            "osdkbybkev2yy14i",
            "24m26ogia9hehfr",
            "xqtvjozlndf8byb9"
        ],
        "points": 66
    },
    {
        "id": "tc90vx9bay4g3nmi",
        "birthDate": "1999-06-05",
        "email": "Reggie21@yahoo.com",
        "firstName": "Weston",
        "lastName": "Wolf",
        "gender": "female",
        "status": true,
        "createdAt": "2014-08-19T22:05:46.772Z",
        "updatedAt": "2014-08-19T22:05:46.772Z",
        "idArray": [
            "318ks0kp292uik9",
            "7lukiphhnis5rk9",
            "9q06a1chagqoajor",
            "324eo3myr1a9vn29",
            "nrtivm2b52buik9",
            "mj6pqcpiydnuq5mi",
            "hb9hlat35xvcmcxr",
            "745xdd52hwd0a4i",
            "gkz7k8t9trlwstt9"
        ],
        "points": 97
    },
    {
        "id": "zy1ax3xe6a1w0zfr",
        "birthDate": "1984-02-29",
        "email": "Shawna35@hotmail.com",
        "firstName": "Ashlynn",
        "lastName": "Kohler",
        "gender": "female",
        "status": true,
        "createdAt": "2014-07-02T12:34:36.087Z",
        "updatedAt": "2014-07-02T12:34:36.087Z",
        "idArray": [
            "7e7lafgntos3v7vi",
            "gfoh7oefbmb49529",
            "xrs73dz9atrtqpvi",
            "6suhyigdj4xnu3di",
            "6548xecnb752vs4i",
            "qufz9taqxcs4te29",
            "o3e9ikb331r4fgvi",
            "d4c5od0qv6gycik9"
        ],
        "points": 19
    },
    {
        "id": "ewe077q8upx2yb9",
        "birthDate": "1941-02-01",
        "email": "Vernie_Boehm3@gmail.com",
        "firstName": "David",
        "lastName": "Champlin",
        "gender": "male",
        "status": true,
        "createdAt": "2014-06-01T04:57:16.049Z",
        "updatedAt": "2014-06-01T04:57:16.049Z",
        "idArray": [
            "hhddtad8zzn6ogvi",
            "kss5ifm7fe597ldi",
            "o8j9qvrgwn42huxr"
        ],
        "points": 16
    },
    {
        "id": "6u9hy2ufwxxhia4i",
        "birthDate": "1980-05-13",
        "email": "Nick.Murray45@yahoo.com",
        "firstName": "Dina",
        "lastName": "Dickinson",
        "gender": "female",
        "status": false,
        "createdAt": "2014-05-02T11:59:19.687Z",
        "updatedAt": "2014-05-02T11:59:19.687Z",
        "idArray": [
            "h4b2ih55giafw29",
            "svhx2l99ptejc3di",
            "n5hzw1dc0ig7rpb9",
            "top1s31ukyxbhuxr"
        ],
        "points": 59
    },
    {
        "id": "9haeqs4ghjdzpvi",
        "birthDate": "1929-08-27",
        "email": "Raina_Dietrich@hotmail.com",
        "firstName": "Courtney",
        "lastName": "Ankunding",
        "gender": "female",
        "status": false,
        "createdAt": "2014-09-07T00:29:42.212Z",
        "updatedAt": "2014-09-07T00:29:42.212Z",
        "idArray": [
            "uohzlm5z2f647vi",
            "nzjnomrubl4eipb9",
            "de4vftrhxu81if6r",
            "nt47222mz3mlhaor",
            "et1s4d390u9885mi",
            "q3sqwb0i0diy66r",
            "8akf00snyp919k9"
        ],
        "points": 22
    },
    {
        "id": "8dus70pu05tawcdi",
        "birthDate": "1992-11-16",
        "email": "Heloise_Beahan3@hotmail.com",
        "firstName": "Cielo",
        "lastName": "Leffler",
        "gender": "female",
        "status": false,
        "createdAt": "2014-10-30T22:13:58.210Z",
        "updatedAt": "2014-10-30T22:13:58.210Z",
        "idArray": [
            "rd9k0cgdi7ap2e29",
            "ziebfsxjmgf1or",
            "12shga4rysyvi",
            "f5ze1ips6hjpds4i",
            "dyp12nqs929vbo6r",
            "vf2of9g9ndnrvn29",
            "m9v800lg9r90ms4i",
            "nmtcrykjbz3q5mi",
            "ls01ijlwk8nwb3xr",
            "g1i5addg2jkvgqfr",
            "85qyp87ok7ggy14i",
            "aaevo44euxt4vx6r",
            "1lqqvjtang0hpvi",
            "trztaam7uar1kyb9",
            "u88pxpn17mhd7vi",
            "z00yjtqwszbvgqfr"
        ],
        "points": 3
    }
]

=== Taper21/local-api/example_raml/examples/user.json
{
    "id": "8dus70pu05tawcdi",
    "birthDate": "1992-11-16",
    "email": "Heloise_Beahan3@hotmail.com",
    "firstName": "Cielo",
    "lastName": "Leffler",
    "gender": "female",
    "status": false,
    "createdAt": "2014-10-30T22:13:58.210Z",
    "updatedAt": "2014-10-30T22:13:58.210Z",
    "idArray": [
        "rd9k0cgdi7ap2e29",
        "ziebfsxjmgf1or",
        "12shga4rysyvi",
        "f5ze1ips6hjpds4i",
        "dyp12nqs929vbo6r",
        "vf2of9g9ndnrvn29",
        "m9v800lg9r90ms4i",
        "nmtcrykjbz3q5mi",
        "ls01ijlwk8nwb3xr",
        "g1i5addg2jkvgqfr",
        "85qyp87ok7ggy14i",
        "aaevo44euxt4vx6r",
        "1lqqvjtang0hpvi",
        "trztaam7uar1kyb9",
        "u88pxpn17mhd7vi",
        "z00yjtqwszbvgqfr"
    ],
    "points": 3
}
